apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devops-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: patricknunest01/frontend:latest
          ports:
            - containerPort: 8000
          env:
            - name: BACKEND_URL
              value: "http://backend.devops-challenge.svc.cluster.local:8080"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: devops-challenge
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
