apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops-challenge
type: Opaque
data:
  POSTGRES_USER: definir_user
  POSTGRES_PASSWORD: definir_password
  POSTGRES_DB: definir_db
